### ISSUE TITLE
Cannot print more than 64 characters

### ISSUE THREAD

**Issue by 48panda48** [BananacraftDevelopment/BananaOS#2]
- Unknown if is always 64 characters it breaks at

 - Could be that the stack size is too small
 - Could be that there isn't enough space in 2 sectors to fit all of the Kernel
 - Could be that C is just weird (it is, but is it causing the problem)
 - Could be that I can't see the issue and it's a logic error

 - I think it may be due to the stack, not sure what, but it seems to be doing funky things

**Comment by lyallstewart** [comment]
Is it just no more than 64 chars in a line of 64 on the whole screen?

**Comment by lyallstewart** [comment]
I mean we could just never print more than 64 chars but it's really not a perfect solution 😂😂

**Comment by 48panda48** [comment]
It's max 64 chars per print statement

**Comment by 48panda48** [comment]
The compiler/linker seems to store strings in a different format/address in the source code after 64 characters

**Comment by lyallstewart** [comment]
Ah ok that's a pain
